pcd2pgm:
  ros__parameters:
    pcd_file: /home/suja/voxel_ws/test.pcd
    odom_to_lidar_odom: [-0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # odom_to_lidar_odom: [-0.16, 0.0, -0.18, -0.523599, 0.0, -1.5707963]
    flag_pass_through: false #直通滤波器 保留在 Z 轴高度范围内的点false  剔除在 Z 轴高度范围内的点true
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.1 #半径滤波器的搜索半径
    thre_z_max: 1.0
    thre_z_min: 0.0  #截取点云的高度范围。通常设为地面以上到雷达安装高度之间，用来提取障碍物。
    thres_point_count: 3
