

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    default_nav_to_pose_bt_xml: "$(find-pkg-share navigation_2d)/config/navigate_w_replanning_time_try_times.xml"
    # default_nav_to_pose_bt_xml: "$(find-pkg-share nav2_bt_navigator)/behavior_trees/navigate_to_pose_w_replanning_goal_patience_and_recovery.xml"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True


controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    progress_checker_plugin: "progress_checker"

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.05

    progress_checker:
      plugin: "nav2_controller::PoseProgressChecker"
      required_movement_radius: 0.01
      required_movement_angle: 0.0175
      movement_time_allowance: 5.0
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.785
      angular_disengage_threshold: 0.3925
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 0.5
      max_angular_accel: 3.924
      simulate_ahead_time: 2.0
      rotate_to_goal_heading: false
      rotate_to_heading_once: true
      closed_loop: true
      use_path_orientations: false
      transform_tolerance: 0.3
      # plugin: "dwb_core::DWBLocalPlanner"
      prune_distance: 1.0
      forward_prune_distance: 2.0
      epsilon: 0.1
      debug_trajectory_details: True
      publish_cost_grid_pc: True
      max_vel_x: 0.6
      min_vel_x: -0.2
      max_vel_y: 0.0
      min_vel_y: 0.0
      max_speed_xy: 0.6
      min_speed_xy: 0.01
      max_vel_theta: 0.5
      min_speed_theta: 0.01
      acc_lim_x: 1.25
      acc_lim_y: 0.0
      acc_lim_theta: 3.924
      decel_lim_x: -1.25
      decel_lim_y: 0.0
      decel_lim_theta: -3.924
      vx_samples: 51
      vy_samples: 0
      vtheta_samples: 21
      sim_time: 2.0
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.05
      trans_stopped_velocity: 0.02
      short_circuit_trajectory_evaluation: false
      include_last_point: false
      stateful: True
      critics: ["PathDist", "GoalDist", "PathAlign", "GoalAlign", "RotateToGoal", "PreferForward", "ObstacleFootprint"] # 
      PathDist.scale: 32.0
      PathDist.aggregation_type: "last"
      GoalDist.scale: 12.0
      GoalDist.aggregation_type: "last"
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      RotateToGoal.scale: 32.0
      RotateToGoal.xy_goal_tolerance: 0.25
      RotateToGoal.trans_stopped_velocity: 0.1
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      PreferForward.scale: 10.0
      PreferForward.penalty: 1.0
      PreferForward.strafe_x: -1.0
      PreferForward.strafe_theta: -1.0
      PreferForward.theta_scale: -0.0
      Twirling.scale: 12.0
      BaseObstacle.scale: 2.2
      BaseObstacle.sum_scores: false
      ObstacleFootprint.scale: 1.0
      ObstacleFootprint.sum_scores: false
      Oscillation.scale: 32.0
      Oscillation.oscillation_reset_dist: 1.0
      Oscillation.oscillation_reset_angle: 0.2
      Oscillation.oscillation_reset_time: -1.0
      Oscillation.x_only_threshold: 0.05

local_costmap:
  local_costmap:
    ros__parameters:
      transform_tolerance: 0.3
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[[-0.40, -0.30], [-0.40, 0.30], [0.40, 0.30], [0.40, -0.30]]"
      always_send_full_costmap: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        max_obstacle_height: 2.0
        min_obstacle_height: -2.0 
        combination_method: 1
        observation_sources: "front_laser back_laser pointcloud"
        front_laser:
          topic: /laser_F/scan_undistort
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0
        back_laser:
          topic: /laser_B/scan_undistort
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0
        pointcloud:
          topic: /lidar_F/pointcloud_undistort
          data_type: "PointCloud2"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 0.5
          min_obstacle_height: -0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.85

global_costmap:
  global_costmap:
    ros__parameters:
      transform_tolerance: 0.3
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      footprint: "[[-0.40, -0.30], [-0.40, 0.30], [0.40, 0.30], [0.40, -0.30]]"
      resolution: 0.05
      track_unknown_space: true
      always_send_full_costmap: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        max_obstacle_height: 2.0
        min_obstacle_height: -2.0 
        combination_method: 1
        observation_sources: "front_laser back_laser pointcloud"
        front_laser:
          topic: /laser_F/scan_undistort
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0 
        back_laser:
          topic: /laser_B/scan_undistort
          data_type: "LaserScan"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 2.0
          min_obstacle_height: -2.0 
        pointcloud:
          topic: /lidar_F/pointcloud_undistort
          data_type: "PointCloud2"
          clearing: True
          marking: True
          raytrace_max_range: 20.0
          raytrace_min_range: 0.01
          obstacle_max_range: 20.0
          obstacle_min_range: 0.01
          max_obstacle_height: 0.5
          min_obstacle_height: -0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.85

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: false
      # plugin: "nav2_smac_planner/SmacPlannerLattice" # SmacPlanner2D SmacPlannerHybrid SmacPlannerLattice
      # tolerance: 0.05                                # tolerance for planning if unable to reach exact pose, in meters
      # downsample_costmap: false                      # whether or not to downsample the map
      # downsampling_factor: 1                         # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      # allow_unknown: false                           # allow traveling in unknown space
      # max_iterations: 1000000                        # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      # max_on_approach_iterations: 1000               # maximum number of iterations to attempt to reach goal once in tolerance
      # max_planning_time: 3.5                         # max time in s for planner to plan, smooth, and upsample. Will scale maximum smoothing and upsampling times based on remaining time after planning.
      # lattice_filepath: "$(find-pkg-share navigation_2d)/config/lattice_omni.json" # For Lattice nodes: Path to the lattice file to use for planning. If not set, will use the default lattice file for the robot.
      # motion_model_for_search: "REEDS_SHEPP" # For Hybrid DUBIN REEDS_SHEPP
      # angle_quantization_bins: 72            # For Hybrid nodes: Number of angle bins for search, must be 1 for 2D node (no angle search)
      # analytic_expansion_ratio: 3.5          # For Hybrid/Lattice nodes: The ratio to attempt analytic expansions during search for final approach.
      # analytic_expansion_max_length: 2.0     # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting (in meters). This should be scaled with minimum turning radius and be no less than 4-5x the minimum radius
      # minimum_turning_radius: 0.5            # For Hybrid: minimum turning radius in m of path / vehicle
      # reverse_penalty: 2.1                   # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      # change_penalty: 0.0                    # For Hybrid nodes: penalty to apply if motion is changing directions, must be >= 0
      # non_straight_penalty: 1.20             # For Hybrid nodes: penalty to apply if motion is non-straight, must be => 1
      # cost_penalty: 2.0                      # For Hybrid nodes: penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      # retrospective_penalty: 0.0             # For Hybrid/Lattice nodes: penalty to prefer later maneuvers before earlier along the path. Saves search time since earlier nodes are not expanded until it is necessary. Must be >= 0.0 and <= 1.0
      # rotation_penalty: 1.0                  # For Lattice node: Penalty to apply only to pure rotate in place commands when using minimum control sets containing rotate in place primitives. This should always be set sufficiently high to weight against this action unless strictly necessary for obstacle avoidance or there may be frequent discontinuities in the plan where it requests the robot to rotate in place to short-cut an otherwise smooth path for marginal path distance savings.
      # lookup_table_size: 20.0                # For Hybrid nodes: Size of the dubin/reeds-sheep distance window to cache, in meters.
      # cache_obstacle_heuristic: True         # For Hybrid nodes: Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.  
      # allow_reverse_expansion: True          # For Lattice nodes: Whether to expand state lattice graph in forward primitives or reverse as well, will double the branching factor at each step.   
      # smooth_path: True                      # For Lattice/Hybrid nodes: Whether or not to smooth the path, always true for 2D nodes.
      # smoother:
      #   max_iterations: 1000
      #   w_smooth: 0.3
      #   w_data: 0.2
      #   tolerance: 1.0e-10
      #   do_refinement: true               # Whether to recursively run the smoother 3 times on the results from prior runs to refine the results further

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.2
    min_rotational_vel: 0.1
    rotational_acc_lim: 3.924
